version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sistema_clima_web
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # Montamos la base de datos para no perder los datos
      - ../clima.db:/app/clima.db
    env_file:
      - ../config/.env.example
    environment:
      - TZ=America/Bogota
    networks:
      - coolify

networks:
  coolify:
    external: true
